# CREATE THE .env FILE BEFORE STARTS THE CONTAINER

ARG VARIANT=18
FROM mcr.microsoft.com/devcontainers/javascript-node:0-${VARIANT}

RUN git config --global --add safe.directory /workspace

EXPOSE 5000